### ISSUE TITLE
Chapter 1 feedback

### ISSUE THREAD

**Issue by jclingan** [ttelang/microprofile-tutorials#1]
Great job! Note that I am careful about how we position MicroProfile and Jakarta EE. They are peer projects. Some background:

More recently Jakarta created the Core Profile to specifically create a profile to support MicroProfile. MicroProfile layers on Core Profile, while Jakarta EE Web Profile and the Jakarta EE 10 platform also layer Core Profile (see the [Jakarta EE 10 spec chart](https://jakarta.ee/release/10/)). That's the layer of commonality.

Developers can build real-world applications using only Jakarta EE APIs. The same is not true of MicroProfile because of its more narrow focus.  To address this, some MicroProfile implementations support MicroProfile, some Jakarta APIs, and many other APIs. [Quarkus](https://quarkus.io/extensions/) takes this approach. Other implementations (like [WildFly](https://www.wildfly.org/downloads/)) support MicroProfile and the full Jakarta EE 10 platform out of the box. Summary: MicroProfile, in and of itself, is not intended to uniquely extend Jakarta EE (until the more recent Jakarta EE Core Profile).

My Chapter 1 feedback is in a google doc is [here](https://docs.google.com/document/d/1RAtXXuffym9g9TqB2B8rAzpR2cpA-00YDDr1kWryAko/edit), and is also attached as a word doc.

[MicroProfile Tutorial - Chapter 1 feedback.docx](https://github.com/ttelang/microprofile-tutorials/files/14186912/MicroProfile.Tutorial.-.Chapter.1.feedback.docx)

**Comment by ttelang** [comment]
Thanks @jclingan for the detailed feedback. I have encorportated most of your changes in this commit https://github.com/ttelang/microprofile-tutorials/commit/2356fb806712da95a8378de5c143333c44bb8213.
