### ISSUE TITLE
Chapter 2: Kumulezee support

### ISSUE THREAD

**Issue by jclingan** [ttelang/microprofile-tutorials#6]
Will there be any issues with listing Kumulezee? It supports MicroProfile 3.3 and this tutorial is intended to target MicroProfile 6.1.

**Comment by ttelang** [comment]
Removed Kumulezee form the list of compatible server implementations. [336f763](https://github.com/ttelang/microprofile-tutorials/commit/336f76396fb7f9bc2b0171e600354d348dc645a8)

**Comment by jclingan** [comment]
I still Kumulezee list listed in Chapter 2 list of compatible implementations
